<a href="https://colab.research.google.com/github/AI-Assignments/AI-ML-Group-Task/blob/main/AI_ML_Group_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

Hyperparameters


In [ ]:
batch_size=2

Dataset

In [ ]:
data={'Day1':[30,40,50,20,15,60], 'Day2':[40,50,20,15,60,70], 'Day3':[50,20,15,60,70,50], 'Target':[20,15,60,70,50,40]}
dataset=pd.DataFrame(data)


In [ ]:
dataset

Day1  Day2  Day3  Target
0    30    40    50      20
1    40    50    20      15
2    50    20    15      60
3    20    15    60      70
4    15    60    70      50
5    60    70    50      40

Drop Target Column

In [ ]:
x=dataset.drop('Target', axis=1)
y=dataset['Target']


In [ ]:
x

Day1  Day2  Day3
0    30    40    50
1    40    50    20
2    50    20    15
3    20    15    60
4    15    60    70
5    60    70    50

Normalizing the dataset

In [ ]:
x_norm=Normalizer(norm='max').fit_transform(x)

In [ ]:
newy=np.reshape(array(y),(1,-1))
newy

array([[20, 15, 60, 70, 50, 40]])

In [ ]:
y_norm=Normalizer(norm='max').fit_transform(newy)

In [ ]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

Training the ANN

In [ ]:
weight_1=uniform(-1,1,(3,2))
weight_2=uniform(-1,1,(2,1))
weight_1

array([[-0.79187718, -0.38917137],
       [-0.20352748,  0.27024708],
       [ 0.05919688, -0.31853183]])

In [ ]:
output_1 = x_norm[0:batch_size]@weight_1
output_1

array([[-0.57875141, -0.33583699],
       [-0.81335047, -0.16850275]])

In [ ]:
actual_output = sigmoid(output_1).numpy()
actual_output

array([[0.35921994, 0.41682107],
       [0.30717699, 0.4579737 ]])

In [ ]:
predicted_output=actual_output@weight_2
predicted_output

array([[-0.70575507],
       [-0.69254392]])