<a href="https://colab.research.google.com/github/AI-Assignments/AI-ML-Group-Task/blob/main/AI_ML_GROUP_TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd 
import numpy as np

In [25]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

Hyperparameters

In [26]:
batch_size=1

Dataset

In [27]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
      'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [28]:
dataset=pd.DataFrame(data)

In [29]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [30]:
X=dataset.drop('Target',axis=1)
y=dataset['Target']

In [31]:
X

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [32]:
X_norm = Normalizer(norm='max').fit_transform(X)

In [33]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [34]:
array(y)

array([20, 15, 60, 70, 50, 40])

In [35]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [36]:
y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [37]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN From Scratch

In [38]:
"""weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])"""

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

Define shape for weights

In [39]:
weight_1=uniform(-1,1,(3,2)) #shape 3 by 2
weight_2=uniform(-1,1,(2,1))

In [40]:
weight_1

array([[-0.91094194,  0.64422118],
       [-0.00683411, -0.43238489],
       [ 0.61269666,  0.16700959]])

In [41]:
weight_2

array([[-0.8866526 ],
       [ 0.58272144]])

Having number of epochs as 100

In [42]:
for i in range(100):
  X_norm[0:batch_size]
  output_1=X_norm[0:batch_size]@weight_1
  act_output=sigmoid(output_1).numpy()
  pred_output=act_output@weight_2
  pred_output=np.reshape(pred_output,(1,-1))

In [43]:
act_output

array([[0.5151614 , 0.55172291]])

In [44]:
y_hat = pred_output
y_hat

array([[-0.13526844]])

In [45]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

Backward propagation

In [46]:
ones_matrix = uniform(1,1,(1,1))
ones_matrix

array([[1.]])

In [47]:
error_k = (y_norm - y_hat) * (y_hat*(ones_matrix - y_hat))
error_k

array([[-0.06464863, -0.05367963, -0.15240062, -0.17433862, -0.13046262,
        -0.10852462]])

In [48]:
error_k

array([[-0.06464863, -0.05367963, -0.15240062, -0.17433862, -0.13046262,
        -0.10852462]])

In [49]:
error_k_const = error_k[0][0]
error_k_const

-0.06464862626775093

Output for node i and j

In [50]:
nj_out = act_output[:,0]
nj_out

array([0.5151614])

In [51]:
ni_out = act_output[:,1] #the 2nd col
ni_out

array([0.55172291])

In [52]:
weight_2_j = uniform(weight_2[0], weight_2[0], (1,1))
weight_2_j

array([[-0.8866526]])

In [53]:
weight_2_i = uniform(weight_2[1], weight_2[1], (1,1))
weight_2_i

array([[0.58272144]])

In [54]:
error_j = error_k_const * weight_2_j * nj_out * (1 - nj_out)
error_j

array([[0.01431704]])

In [55]:
error_i = error_k_const * weight_2_i * ni_out * (1 - ni_out)
error_i

array([[-0.00931725]])

Delta Rule

In [56]:
learning_rate = 0.03 #from the slides

In [57]:
hidden_layer_errors = np.concatenate((error_j, error_i), axis=1)
hidden_layer_errors

array([[ 0.01431704, -0.00931725]])

In [58]:
hidden_layer_outputs = np.concatenate((nj_out, ni_out), axis=0)

In [59]:
hidden_layer_outputs

array([0.5151614 , 0.55172291])

In [60]:
hidden_layer_outputs = np.reshape(hidden_layer_outputs, (1,2))
hidden_layer_outputs

array([[0.5151614 , 0.55172291]])

Finding delta for weight_1

In [61]:
delta_weight_1 = learning_rate * hidden_layer_errors * hidden_layer_outputs
delta_weight_1

array([[ 0.00022127, -0.00015422]])

Adjusting weight_1

In [62]:
new_weight_1 = weight_1 + delta_weight_1
new_weight_1

array([[-0.91072067,  0.64406696],
       [-0.00661285, -0.43253911],
       [ 0.61291793,  0.16685537]])

Finding delta for weight_2

In [63]:
error_output_layer = np.reshape(array(error_k_const), (1,1))
error_output_layer

array([[-0.06464863]])

In [64]:
delta_weight_2 = learning_rate * error_output_layer * pred_output
delta_weight_2

array([[0.00026235]])

Adjusting weight 2

In [65]:
new_weight_2 = weight_2 + delta_weight_2
new_weight_2

array([[-0.88639026],
       [ 0.58298378]])

In [66]:
i

99

In [67]:
weight_1 = new_weight_1
weight_2 = new_weight_2

In [68]:
weight_1

array([[-0.91072067,  0.64406696],
       [-0.00661285, -0.43253911],
       [ 0.61291793,  0.16685537]])

In [69]:
weight_2

array([[-0.88639026],
       [ 0.58298378]])